---
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.5
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install OS dependencies
          command: |
            sudo apt update -y
            sudo apt install -y libsasl2-dev python-dev libldap2-dev libssl-dev
      - run:
          name: Install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            make develop
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make coverage
      - run:
          command: |
            sudo pip install codecov
            codecov
          when: always

  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-jessie
